SUPABASE_URL = "https://vhdgsfppibtmjtulxdvd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoZGdzZnBwaWJ0bWp0dWx4ZHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5MDA2MTEsImV4cCI6MjA5ODQ3NjYxMX0.wJiBpyQstdMSdir5Fv69sglL5T35wqy2OcXdrfN5dNo"
